const questionBank = [
    
    // Pergunta 1: Definição de Energia Térmica
    {
        id: "t1",
        type: "mc",
        questionText: `
            According to the provided text, how is **Thermal Energy** generated?
        `,
        options: [
            { letter: "A", text: "(A) By the combination of ambient temperature and relative humidity." },
            { letter: "B", text: "(B) By the movement of minuscule particles." },
            { letter: "C", text: "(C) By the difference between hot and cold objects." },
            { letter: "D", text: "(D) By the heat index (apparent temperature)." },
            { letter: "E", text: "(E) By the heat sensors in a digital thermometer." }
        ],
        correctAnswer: "B",
        videoUrl: "",
        hints: [
            "Dica 1: Procure a seção 'Thermal Energy' na imagem 'energy.jpg'.",
            "Dica 2: O texto diz que essa energia é gerada por 'miniscule particles'.",
            "Dica 3: Esta é a definição física fundamental de Energia Térmica dada no material."
        ]
    },

    // Pergunta 2: Diferença entre Calor e Temperatura
    {
        id: "t2",
        type: "mc",
        questionText: `
            Which of the following statements correctly distinguishes between **Heat** and **Temperature**, according to the text?
        `,
        options: [
            { letter: "A", text: "(A) Heat is how hot or cold something is, while temperature is energy from movement." },
            { letter: "B", text: "(B) Thermal energy comes from heat and temperature, but heat is the movement of energy from hot to cold." },
            { letter: "C", text: "(C) Temperature is heat, and heat is literally how hot or cold something is." },
            { letter: "D", text: "(D) Heat is measured by thermometers, and temperature is the metric used globally." },
            { letter: "E", text: "(E) Heat is thermal energy, and temperature is the official language for academic purposes." }
        ],
        correctAnswer: "B",
        videoUrl: "",
        hints: [
            "Dica 1: A diferença é abordada na seção 'Thermal Energy' (imagem 'energy.jpg').",
            "Dica 2: Temperatura é sobre 'how hot or cold something is'.",
            "Dica 3: Calor (Heat) é o que 'moves it from hot to cold'."
        ]
    },

    // Pergunta 3: Definição de Temperatura
    {
        id: "t3",
        type: "mc",
        questionText: `
            The provided text defines **Temperature** as:
        `,
        options: [
            { letter: "A", text: "(A) The energy that comes from heat." },
            { letter: "B", text: "(B) The way the ambient temperature feels like." },
            { letter: "C", text: "(C) Literally how hot or cold something is." },
            { letter: "D", text: "(D) The movement of thermal energy." },
            { letter: "E", "text": "(E) The official language for engineering." }
        ],
        correctAnswer: "C",
        videoUrl: "",
        hints: [
            "Dica 1: Procure a definição de Temperatura nas imagens 'energy.jpg' e 'asd.jpg'.",
            "Dica 2: A definição literal é 'how hot or cold something is'.",
            "Dica 3: Não confunda com a definição de Calor (Heat)."
        ]
    },

    // Pergunta 4: O que é o Heat Index (Índice de Calor)
    {
        id: "t4",
        type: "mc",
        questionText: `
            What is the **Heat Index**, also known as the apparent temperature?
        `,
        options: [
            { letter: "A", text: "(A) The reading of a mercury thermometer." },
            { letter: "B", text: "(B) The thermal energy generated by particle movement." },
            { letter: "C", text: "(C) The temperature scale used worldwide." },
            { letter: "D", text: "(D) What the temperature feels like to our body, combined with air temperature and relative humidity." },
            { letter: "E", "text": "(E) The difference between the Celsius and Kelvin scales." }
        ],
        correctAnswer: "D",
        videoUrl: "",
        hints: [
            "Dica 1: Procure a seção 'Heat Index' na imagem 'heat.jpg'.",
            "Dica 2: O índice é a sensação de temperatura ('feels like').",
            "Dica 3: Ele combina dois fatores principais: temperatura ambiente e umidade relativa."
        ]
    },

    // Pergunta 5: Escala de Temperatura Mais Utilizada
    {
        id: "t5",
        type: "mc",
        questionText: `
            According to the 'Scales' chart, which temperature scale is the **most used throughout the world** and considered the metric one?
        `,
        options: [
            { letter: "A", text: "(A) Fahrenheit" },
            { letter: "B", text: "(B) Kelvin" },
            { letter: "C", text: "(C) Celsius" },
            { letter: "D", text: "(D) Rankine" },
            { letter: "E", "text": "(E) Newton" }
        ],
        correctAnswer: "C",
        videoUrl: "",
        hints: [
            "Dica 1: Consulte a tabela na imagem 'ceus.jpg'.",
            "Dica 2: O símbolo desta escala é °C.",
            "Dica 3: Esta escala é a base para o sistema métrico."
        ]
    },

    // Pergunta 6: Escala de Temperatura para Fins Acadêmicos
    {
        id: "t6",
        type: "mc",
        questionText: `
            Which temperature scale is **widely used for Academic purposes**, such as in science and engineering?
        `,
        options: [
            { letter: "A", text: "(A) Celsius (°C)" },
            { letter: "B", text: "(B) Fahrenheit (°F)" },
            { letter: "C", text: "(C) Kelvin (K)" },
            { letter: "D", text: "(D) Rankine (R)" },
            { letter: "E", "text": "(E) Réaumur (°Ré)" }
        ],
        correctAnswer: "C",
        videoUrl: "",
        hints: [
            "Dica 1: Consulte a última linha da tabela na imagem 'ceus.jpg'.",
            "Dica 2: O símbolo desta escala é apenas 'K', sem o símbolo de grau (°).",
            "Dica 3: É a escala preferida para trabalhos científicos e de pesquisa."
        ]
    },

    // Pergunta 7: Instrumento de Medição
    {
        id: "t7",
        type: "mc",
        questionText: `
            What is the object used to **measure temperature**?
        `,
        options: [
            { letter: "A", text: "(A) Heat Index" },
            { letter: "B", text: "(B) Heat Sensor" },
            { letter: "C", text: "(C) Barometer" },
            { letter: "D", text: "(D) Thermometer" },
            { letter: "E", "text": "(E) Hygrometer" }
        ],
        correctAnswer: "D",
        videoUrl: "",
        hints: [
            "Dica 1: O instrumento é mencionado na seção 'Thermal Energy' e 'Temperature & Thermometers'.",
            "Dica 2: É o objeto que as pessoas usam para verificar se estão com febre.",
            "Dica 3: O nome do instrumento vem de 'thermo' (calor) e 'meter' (medida)."
        ]
    },

    // Pergunta 8: Escala de Temperatura com uso na língua inglesa
    {
        id: "t8",
        type: "mc",
        questionText: `
            Which temperature scale is **widely used in countries where English is the official language**?
        `,
        options: [
            { letter: "A", text: "(A) Celsius" },
            { letter: "B", text: "(B) Kelvin" },
            { letter: "C", text: "(C) Fahrenheit" },
            { letter: "D", text: "(D) Réaumur" },
            { letter: "E", "text": "(E) Newton" }
        ],
        correctAnswer: "C",
        videoUrl: "",
        hints: [
            "Dica 1: Consulte a tabela na imagem 'ceus.jpg'.",
            "Dica 2: O símbolo desta escala é °F.",
            "Dica 3: É usada principalmente nos EUA e alguns outros países de língua inglesa."
        ]
    },

    // Pergunta 9: Tipo de Termômetro Sendo Substituído
    {
        id: "t9",
        type: "mc",
        questionText: `
            Which type of thermometer is being replaced by digital ones because it is a 'bulb glass with mercury'?
        `,
        options: [
            { letter: "A", text: "(A) Heat Sensor Thermometer" },
            { letter: "B", text: "(B) Digital Thermometer" },
            { letter: "C", text: "(C) Mercury Thermometer" },
            { letter: "D", text: "(D) Apparent Temperature Thermometer" },
            { letter: "E", "text": "(E) Academic Thermometer" }
        ],
        correctAnswer: "C",
        videoUrl: "",
        hints: [
            "Dica 1: Procure a seção 'Temperature & Thermometers' na imagem 'asd.jpg'.",
            "Dica 2: O texto menciona que este tipo está sendo substituído.",
            "Dica 3: Este instrumento tradicional contém um metal líquido perigoso."
        ]
    },

    // Pergunta 10: Fatores que Afetam a Sensação de Temperatura
    {
        id: "t10",
        type: "mc",
        questionText: `
            The way the ambient temperature feels depends on four factors mentioned in the text. Which of the following is **NOT** one of them?
        `,
        options: [
            { letter: "A", text: "(A) The temperature of the air itself." },
            { letter: "B", text: "(B) Relative humidity." },
            { letter: "C", text: "(C) Our body's temperature." },
            { letter: "D", text: "(D) The intensity of heat transfer from hot to cold." },
            { letter: "E", "text": "(E) The combination of air temperature and relative humidity (Heat Index)." }
        ],
        correctAnswer: "D",
        videoUrl: "",
        hints: [
            "Dica 1: Consulte o parágrafo sobre 'Heat Index' na imagem 'heat.jpg'.",
            "Dica 2: Os fatores são: temperatura do ar, umidade relativa e temperatura corporal.",
            "Dica 3: A opção incorreta descreve o que é Calor (Heat), não o que afeta o Índice de Calor (Heat Index)."
        ]
    },
    {
        id: "t11",
        type: "mc",
        questionText: `
            What is a **Temperature Scale**?
        `,
        options: [
            { letter: "A", text: "(A) The feeling of heat on the body." },
            { letter: "B", text: "(B) The thermal energy from minuscule particles." },
            { letter: "C", text: "(C) One of the ways to measure (or indicate) the temperature through a unit of measurement." },
            { letter: "D", text: "(D) The thermometer that works with heat sensors." },
            { letter: "E", "text": "(E) The combination of temperature and wind." }
        ],
        correctAnswer: "C",
        videoUrl: "",
        hints: [
            "Dica 1: Procure a seção 'Temperature Scales' na imagem 'asd.jpg'.",
            "Dica 2: A escala é a base para quantificar a temperatura.",
            "Dica 3: É o sistema usado para definir unidades como Celsius e Fahrenheit."
        ]
    },

    // Pergunta 12: Qual o papel do Vento (Wind)
    {
        id: "t12",
        type: "mc",
        questionText: `
            The text mentions that if you are in Fortaleza and feel the wind on a hot day, it automatically feels cooler. This phenomenon is a direct consequence of:
        `,
        options: [
            { letter: "A", text: "(A) The Kelvin scale being used for academic purposes." },
            { letter: "B", text: "(B) The wind increasing the relative humidity, thus lowering the temperature." },
            { letter: "C", text: "(C) The wind affecting the **Heat Index** (apparent temperature) by promoting faster heat loss from the body." },
            { letter: "D", text: "(D) The wind carrying away minuscule particles that generate thermal energy." },
            { letter: "E", "text": "(E) The movement of heat from cold to hot." }
        ],
        correctAnswer: "C",
        videoUrl: "",
        hints: [
            "Dica 1: O texto do 'Heat Index' (imagem 'heat.jpg') introduz a questão do vento.",
            "Dica 2: O vento influencia como o corpo percebe o calor — ele está relacionado ao Índice de Calor (Heat Index).",
            "Dica 3: No contexto, o vento é um fator que altera a 'sensação' de temperatura, ou seja, a temperatura aparente (apparent temperature)."
        ]
    },

    // Pergunta 13: O que os Termômetros Medem
    {
        id: "t13",
        type: "mc",
        questionText: `
            Thermometers are instruments used to measure:
        `,
        options: [
            { letter: "A", text: "(A) Thermal Energy." },
            { letter: "B", text: "(B) The movement of minuscule particles." },
            { letter: "C", text: "(C) Heat (the movement of energy)." },
            { letter: "D", text: "(D) Temperature (how hot or cold something is)." },
            { letter: "E", "text": "(E) Relative humidity." }
        ],
        correctAnswer: "D",
        videoUrl: "",
        hints: [
            "Dica 1: A seção 'Temperature & Thermometers' (imagem 'asd.jpg') explica isso.",
            "Dica 2: O instrumento mede a intensidade do estado térmico, não a transferência de energia.",
            "Dica 3: O texto diz 'To measure the temperature, we have an object: A thermometer'."
        ]
    },

    // Pergunta 14: Escalas Comuns (Múltipla Escolha)
    {
        id: "t14",
        type: "mc",
        questionText: `
            Nowadays, three temperature scales are most commonly used. Which set of scales correctly lists these three, according to the text?
        `,
        options: [
            { letter: "A", text: "(A) Celsius, Rankine, and Newton." },
            { letter: "B", text: "(B) Fahrenheit, Réaumur, and Kelvin." },
            { letter: "C", text: "(C) Celsius, Fahrenheit, and Kelvin." },
            { letter: "D", text: "(D) Fahrenheit, Rankine, and Celsius." },
            { letter: "E", "text": "(E) Newton, Kelvin, and Celsius." }
        ],
        correctAnswer: "C",
        videoUrl: "",
        hints: [
            "Dica 1: A lista está na tabela e introdução das escalas (imagens 'ceus.jpg' e 'asd.jpg').",
            "Dica 2: As três listadas são a métrica, a usada em países de língua inglesa e a acadêmica.",
            "Dica 3: As três são Celsius, Fahrenheit e Kelvin."
        ]
    },

    // Pergunta 15: Termômetros Digitais
    {
        id: "t15",
        type: "mc",
        questionText: `
            How do **Digital Thermometers** work?
        `,
        options: [
            { letter: "A", text: "(A) By using a bulb glass filled with mercury." },
            { letter: "B", text: "(B) By converting thermal energy into Fahrenheit readings." },
            { letter: "C", text: "(C) By the movement of minuscule particles." },
            { letter: "D", text: "(D) By using heat sensors to show the body temperature." },
            { letter: "E", "text": "(E) By measuring the relative humidity of the air." }
        ],
        correctAnswer: "D",
        videoUrl: "",
        hints: [
            "Dica 1: Procure a seção 'Temperature & Thermometers' na imagem 'asd.jpg'.",
            "Dica 2: O texto compara o termômetro digital com o de mercúrio.",
            "Dica 3: O elemento-chave do digital é o 'heat sensor'."
        ]
    },

    // Pergunta 16: Analogia da Água Fervente
    {
        id: "t16",
        type: "mc",
        questionText: `
            The text uses the phrase **'If you heat the water, it boils'** as an example to introduce the concept of:
        `,
        options: [
            { letter: "A", text: "(A) The Kelvin scale." },
            { letter: "B", text: "(B) The Heat Index." },
            { letter: "C", text: "(C) Thermal Energy." },
            { letter: "D", text: "(D) Relative humidity." },
            { letter: "E", "text": "(E) A spontaneous decision." }
        ],
        correctAnswer: "C",
        videoUrl: "",
        hints: [
            "Dica 1: Consulte o início da seção 'Thermal Energy' (imagem 'energy.jpg').",
            "Dica 2: A frase é usada para fazer uma conexão direta com a energia do calor.",
            "Dica 3: É um exemplo de como o calor (heat) se relaciona com a Energia Térmica."
        ]
    },

    // Pergunta 17: Significado de "Heat" no contexto de transferência
    {
        id: "t17",
        type: "mc",
        questionText: `
            In the context of thermal energy, the text states that **Heat** is literally:
        `,
        options: [
            { letter: "A", text: "(A) How hot or cold something is." },
            { letter: "B", text: "(B) The way the ambient temperature feels." },
            { letter: "C", text: "(C) What moves from hot to cold." },
            { letter: "D", text: "(D) The energy generated by the movement of minuscule particles." },
            { letter: "E", "text": "(E) The measure indicated by a mercury thermometer." }
        ],
        correctAnswer: "C",
        videoUrl: "",
        hints: [
            "Dica 1: O texto faz uma distinção clara entre Heat e Temperature (imagem 'energy.jpg').",
            "Dica 2: Calor (Heat) é a transferência.",
            "Dica 3: Temperatura é o estado (quão quente/frio) e calor é o movimento (hot to cold)."
        ]
    },

    // Pergunta 18: Unidade do Kelvin
    {
        id: "t18",
        type: "mc",
        questionText: `
            The official symbol for the **Kelvin** temperature scale is:
        `,
        options: [
            { letter: "A", text: "(A) °C" },
            { letter: "B", text: "(B) °F" },
            { letter: "C", text: "(C) K" },
            { letter: "D", text: "(D) T" },
            { letter: "E", "text": "(E) TE" }
        ],
        correctAnswer: "C",
        videoUrl: "",
        hints: [
            "Dica 1: Consulte a tabela na imagem 'ceus.jpg'.",
            "Dica 2: O Kelvin não usa o símbolo de grau (°).",
            "Dica 3: É a unidade do Sistema Internacional (SI) para temperatura termodinâmica."
        ]
    },

    // Pergunta 19: Termômetro de Mercúrio
    {
        id: "t19",
        type: "mc",
        questionText: `
            The **Mercury Thermometer** is described as a:
        `,
        options: [
            { letter: "A", text: "(A) Digital one that works with heat sensors." },
            { letter: "B", text: "(B) Bulb glass with mercury." },
            { letter: "C", text: "(C) Device that measures apparent temperature." },
            { letter: "D", text: "(D) Tool used only for academic purposes." },
            { letter: "E", "text": "(E) Scale widely used in English-speaking countries." }
        ],
        correctAnswer: "B",
        videoUrl: "",
        hints: [
            "Dica 1: Procure a descrição na seção 'Temperature & Thermometers' (imagem 'asd.jpg').",
            "Dica 2: O mercúrio é o líquido que se expande dentro do tubo.",
            "Dica 3: O texto o descreve como 'a bulb glass with mercury'."
        ]
    },

    // Pergunta 20: Temperatura Aparente
    {
        id: "t20",
        type: "mc",
        questionText: `
            The term **Apparent Temperature** is another name for:
        `,
        options: [
            { letter: "A", text: "(A) Thermal Energy." },
            { letter: "B", text: "(B) Relative Humidity." },
            { letter: "C", text: "(C) The Kelvin Scale." },
            { letter: "D", text: "(D) The Heat Index." },
            { letter: "E", "text": "(E) The Celsius Metric." }
        ],
        correctAnswer: "D",
        videoUrl: "",
        hints: [
            "Dica 1: Consulte o parágrafo sobre 'Heat Index' (imagem 'heat.jpg').",
            "Dica 2: O texto diz que é 'also known as the apparent temperature'.",
            "Dica 3: Refere-se à temperatura que o corpo sente, não a que é medida diretamente no ar."
        ]
    }
];